services:
    postgres:
        image: postgres:15.1
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=pass
            - POSTGRES_DB=techtest
        volumes:
            - tech-test-database-files:/var/lib/postgresql/data

volumes:
    tech-test-database-files:
